# Generated by Django 6.0.2 on 2026-03-21 00:52

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', common.fields.UnsignedBigAutoField(db_column='state_id', primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_column='state_code', max_length=2, unique=True)),
                ('state_name', models.CharField(db_column='state_name', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'states',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('timezone_id', common.fields.UnsignedBigAutoField(db_column='timezone_id', primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(db_column='timezone_name', max_length=6, unique=True)),
            ],
            options={
                'db_table': 'timezones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', common.fields.UnsignedBigAutoField(db_column='city_id', primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='city_name', max_length=50)),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=6, max_digits=9)),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.RESTRICT, to='core.state')),
                ('timezone', models.ForeignKey(db_column='timezone_id', on_delete=django.db.models.deletion.RESTRICT, to='core.timezone')),
            ],
            options={
                'db_table': 'cities',
                'managed': True,
                'indexes': [models.Index(fields=['state'], name='ix_cities_state'), models.Index(fields=['timezone'], name='fk_cities_timezone')],
                'constraints': [models.UniqueConstraint(fields=('state', 'city_name'), name='uq_cities_state_city'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='chk_cities_lat'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='chk_cities_lon')],
            },
        ),
    ]
