# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(db_column='city_id', primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='city_name', max_length=50)),
                ('latitude', models.DecimalField(db_column='latitude', decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_column='longitude', decimal_places=6, max_digits=9)),
                ('location', models.BinaryField(db_column='location')),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.BigAutoField(db_column='state_id', primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_column='state_code', max_length=2, unique=True)),
                ('state_name', models.CharField(db_column='state_name', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('timezone_id', models.BigAutoField(db_column='timezone_id', primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(db_column='timezone_name', max_length=6, unique=True)),
            ],
            options={
                'db_table': 'timezones',
                'managed': False,
            },
        ),
    ]
