# Generated by Django 6.0.2 on 2026-03-20 20:47

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=common.fields.UnsignedBigAutoField(db_column='city_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_id',
            field=common.fields.UnsignedBigAutoField(db_column='state_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='timezone_id',
            field=common.fields.UnsignedBigAutoField(db_column='timezone_id', primary_key=True, serialize=False),
        ),
    ]
