# Generated by Django 6.0.2 on 2026-03-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'managed': True},
        ),
    ]
