# Generated by Django 6.0.2 on 2026-03-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_city_id_alter_state_state_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='spx_cities_location',
        ),
        migrations.RemoveField(
            model_name='city',
            name='location',
        ),
    ]
