# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.BigAutoField(db_column='listing_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('price_amount', models.DecimalField(db_column='price_amount', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('view_count', models.PositiveBigIntegerField(db_column='view_count', default=0)),
            ],
            options={
                'db_table': 'listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListingAttributeValue',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('value_int', models.BigIntegerField(blank=True, db_column='value_int', null=True)),
                ('value_decimal', models.DecimalField(blank=True, db_column='value_decimal', decimal_places=6, max_digits=18, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, db_column='value_datetime', null=True)),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
            ],
            options={
                'db_table': 'listing_attribute_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('image_id', models.BigAutoField(db_column='image_id', primary_key=True, serialize=False)),
                ('image_url', models.CharField(db_column='image_url', max_length=512)),
                ('display_order', models.IntegerField(db_column='display_order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
            ],
            options={
                'db_table': 'listing_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('status_id', models.BigAutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='status_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'listing_status',
                'managed': False,
            },
        ),
    ]
