# Generated by Django 6.0.2 on 2026-03-17 15:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('status_id', models.BigAutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='status_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'listing_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.BigAutoField(db_column='listing_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('price_amount', models.DecimalField(db_column='price_amount', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('view_count', models.BigIntegerField(db_column='view_count', default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.category')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.RESTRICT, to='core.city')),
                ('condition', models.ForeignKey(db_column='condition_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.itemcondition')),
                ('seller_user', models.ForeignKey(db_column='seller_user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, to='listings.listingstatus')),
            ],
            options={
                'db_table': 'listings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListingAttributeValue',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('value_int', models.BigIntegerField(blank=True, db_column='value_int', default=None, null=True)),
                ('value_decimal', models.DecimalField(blank=True, db_column='value_decimal', decimal_places=6, default=None, max_digits=18, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, db_column='value_datetime', default=None, null=True)),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', default=None, null=True)),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.attribute')),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('value_text', models.ForeignKey(blank=True, db_column='value_text_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.allowedattributevalue')),
            ],
            options={
                'db_table': 'listing_attribute_values',
                'managed': True,
                'indexes': [models.Index(fields=['attribute'], name='ix_lav_attribute'), models.Index(fields=['value_text'], name='fk_lav_value_text')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'attribute'), name='listing_id')],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('image_id', models.BigAutoField(db_column='image_id', primary_key=True, serialize=False)),
                ('image_url', models.CharField(db_column='image_url', max_length=512)),
                ('display_order', models.IntegerField(db_column='display_order')),
                ('uploaded_at', models.DateTimeField(db_column='uploaded_at', default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'db_table': 'listing_images',
                'managed': True,
                'indexes': [models.Index(fields=['listing'], name='ix_listing_images_listing')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'display_order'), name='uq_listing_images_listing_order')],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller_user'], name='ix_listings_seller'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category'], name='ix_listings_category'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['condition'], name='ix_listings_condition'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='ix_listings_city'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='fk_listings_status'),
        ),
    ]
