# Generated by Django 6.0.2 on 2026-03-20 20:47

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=common.fields.UnsignedBigAutoField(db_column='listing_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listingattributevalue',
            name='id',
            field=common.fields.UnsignedBigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image_id',
            field=common.fields.UnsignedBigAutoField(db_column='image_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listingstatus',
            name='status_id',
            field=common.fields.UnsignedBigAutoField(db_column='status_id', primary_key=True, serialize=False),
        ),
    ]
