# Generated by Django 6.0.2 on 2026-03-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='listingattributevalue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='listingstatus',
            options={'managed': True},
        ),
    ]
