# Generated by Django 6.0.2 on 2026-03-21 00:52

import common.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationActionType',
            fields=[
                ('action_type_id', common.fields.UnsignedBigAutoField(db_column='action_type_id', primary_key=True, serialize=False)),
                ('action_type_name', models.CharField(db_column='action_type_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'administration_action_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', common.fields.UnsignedBigAutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role_name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdministrationAction',
            fields=[
                ('action_id', common.fields.UnsignedBigAutoField(db_column='action_id', primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(db_column='actor_user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='administration_actions_as_actor', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing')),
                ('target_user', models.ForeignKey(blank=True, db_column='target_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_actions_as_target', to=settings.AUTH_USER_MODEL)),
                ('action_type', models.ForeignKey(db_column='action_type_id', on_delete=django.db.models.deletion.RESTRICT, to='admin_ops.administrationactiontype')),
            ],
            options={
                'db_table': 'administration_actions',
                'managed': True,
                'indexes': [models.Index(fields=['actor_user'], name='ix_admin_actions_actor'), models.Index(fields=['listing'], name='ix_admin_actions_listing'), models.Index(fields=['target_user'], name='ix_admin_actions_target_user'), models.Index(fields=['action_type'], name='fk_admin_actions_action_type')],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', common.fields.UnsignedBigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(db_column='assigned_at', default=django.utils.timezone.now)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='admin_ops.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_role_assignments',
                'managed': True,
                'indexes': [models.Index(fields=['role'], name='ix_ura_role')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='user_id')],
            },
        ),
    ]
