# Generated by Django 6.0.2 on 2026-03-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userroleassignment',
            options={'managed': True},
        ),
    ]
