# Generated by Django 6.0.2 on 2026-03-20 20:47

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0002_create_administration_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationaction',
            name='action_id',
            field=common.fields.UnsignedBigAutoField(db_column='action_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrationactiontype',
            name='action_type_id',
            field=common.fields.UnsignedBigAutoField(db_column='action_type_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=common.fields.UnsignedBigAutoField(db_column='role_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='id',
            field=common.fields.UnsignedBigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
