# tracking/json_snapshots.py
# Generated by ChatGPT on 3-8-2026 by JSF.

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone as datetime_timezone
from decimal import Decimal
from typing import Any, Optional

from django.apps import apps
from django.db import connection, transaction
from django.utils import timezone

from .models import ListingMetadataSnapshot


@dataclass(slots=True)
class ListingMetadataSnapshotData:
    """
    High-level deserialized representation of one listing metadata snapshot.

    The field names intentionally mirror the persisted JSON shape.
    """

    Title: str
    CityName: str
    Condition: str
    CreatedAt: str
    StateCode: str
    UpdatedAt: Optional[str]
    Attributes: dict[str, str] = field(default_factory=dict)
    Image: Optional[str] = None
    PriceAmount: float = 0.0
    CategoryName: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "Title": self.Title,
            "CityName": self.CityName,
            "Condition": self.Condition,
            "CreatedAt": self.CreatedAt,
            "StateCode": self.StateCode,
            "UpdatedAt": self.UpdatedAt,
            "Attributes": dict(self.Attributes),
            "Image": self.Image,
            "PriceAmount": self.PriceAmount,
            "CategoryName": self.CategoryName,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ListingMetadataSnapshotData":
        return cls(
            Title=str(data.get("Title", "")),
            CityName=str(data.get("CityName", "")),
            Condition=str(data.get("Condition", "")),
            CreatedAt=str(data.get("CreatedAt", "")),
            StateCode=str(data.get("StateCode", "")),
            UpdatedAt=_optional_string(data.get("UpdatedAt")),
            Attributes=_coerce_attributes(data.get("Attributes")),
            Image=_optional_string(data.get("Image")),
            PriceAmount=_coerce_float(data.get("PriceAmount")),
            CategoryName=str(data.get("CategoryName", "")),
        )

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=4)


def get_snapshot(listing_id: int) -> ListingMetadataSnapshotData:
    """
    Read and deserialize one listing metadata snapshot.

    If the snapshot row does not exist yet, this function compiles it first
    from normalized source-of-truth data.
    """
    try:
        snapshot: ListingMetadataSnapshot = ListingMetadataSnapshot.objects.only(
            "compiled_json"
        ).get(listing_id=listing_id)
    except ListingMetadataSnapshot.DoesNotExist:
        refresh_snapshot(listing_id)
        snapshot = ListingMetadataSnapshot.objects.only("compiled_json").get(
            listing_id=listing_id
        )

    compiled_json: Any = snapshot.compiled_json
    if isinstance(compiled_json, str):
        compiled_json = json.loads(compiled_json)

    if not isinstance(compiled_json, dict):
        raise ValueError(
            f"listing_metadata_snapshots.compiled_json for listing_id={listing_id} "
            f"is not a JSON object."
        )

    return ListingMetadataSnapshotData.from_dict(compiled_json)


def refresh_snapshot(listing_id: int) -> None:
    """
    Rebuild and persist the listing metadata snapshot for one listing.
    """
    with transaction.atomic():
        snapshot_data: ListingMetadataSnapshotData = _build_snapshot_data(listing_id)

        ListingMetadataSnapshot.objects.update_or_create(
            listing_id=listing_id,
            defaults={
                "compiled_json": snapshot_data.to_dict(),
                "compiled_at": timezone.now(),
            },
        )


def _build_snapshot_data(listing_id: int) -> ListingMetadataSnapshotData:
    listing_row: dict[str, Any] = _fetch_listing_core_row(listing_id)
    primary_image_url: Optional[str] = _fetch_primary_image_url(listing_id)
    attributes: dict[str, str] = _fetch_attribute_map(listing_id)

    return ListingMetadataSnapshotData(
        Title=str(listing_row["title"]),
        CityName=str(listing_row["city_name"]),
        Condition=str(listing_row["condition_name"]),
        CreatedAt=_datetime_to_snapshot_string(listing_row["created_at"]) or "",
        StateCode=str(listing_row["state_code"]),
        UpdatedAt=_datetime_to_snapshot_string(listing_row["updated_at"]),
        Attributes=attributes,
        Image=primary_image_url,
        PriceAmount=_decimal_to_float(listing_row["price_amount"]),
        CategoryName=str(listing_row["category_name"]),
    )


def _fetch_listing_core_row(listing_id: int) -> dict[str, Any]:
    sql: str = """
        SELECT
            l.listing_id,
            l.title,
            l.price_amount,
            l.created_at,
            l.updated_at,
            c.city_name,
            s.state_code,
            ic.condition_name,
            cat.name AS category_name
        FROM listings AS l
        INNER JOIN cities AS c
            ON c.city_id = l.city_id
        INNER JOIN states AS s
            ON s.state_id = c.state_id
        INNER JOIN item_conditions AS ic
            ON ic.condition_id = l.condition_id
        INNER JOIN categories AS cat
            ON cat.category_id = l.category_id
        WHERE l.listing_id = %s
        LIMIT 1
    """

    row: Optional[dict[str, Any]] = _fetch_one_dict(sql, [listing_id])
    if row is None:
        listing_model: Any = apps.get_model("listings", "Listing")
        raise listing_model.DoesNotExist(
            f"Listing with listing_id={listing_id} does not exist."
        )

    return row


def _fetch_primary_image_url(listing_id: int) -> Optional[str]:
    sql: str = """
        SELECT
            li.image_url
        FROM listing_images AS li
        WHERE li.listing_id = %s
          AND li.display_order = 0
        LIMIT 1
    """

    row: Optional[dict[str, Any]] = _fetch_one_dict(sql, [listing_id])
    if row is None:
        return None

    return _optional_string(row.get("image_url"))


def _fetch_attribute_map(listing_id: int) -> dict[str, str]:
    sql: str = """
        SELECT
            a.attribute_key,
            avt.value_type_name,
            lav.value_int,
            lav.value_decimal,
            lav.value_datetime,
            lav.value_bool,
            aav.allowed_value_label AS value_text
        FROM listing_attribute_values AS lav
        INNER JOIN attributes AS a
            ON a.attribute_id = lav.attribute_id
        INNER JOIN attribute_value_type AS avt
            ON avt.value_type_id = a.value_type_id
        LEFT JOIN allowed_attribute_values AS aav
            ON aav.allowed_value_id = lav.value_text_id
        WHERE lav.listing_id = %s
        ORDER BY a.attribute_key ASC
    """

    rows: list[dict[str, Any]] = _fetch_all_dicts(sql, [listing_id])
    attributes: dict[str, str] = {}

    for row in rows:
        attribute_key: str = str(row["attribute_key"])
        attributes[attribute_key] = _attribute_row_to_snapshot_string(row)

    return attributes


def _attribute_row_to_snapshot_string(row: dict[str, Any]) -> str:
    value_type_name: str = str(row["value_type_name"]).strip().lower()

    if value_type_name in {"int", "integer"}:
        value_int: Any = row.get("value_int")
        return "" if value_int is None else str(value_int)

    if value_type_name == "decimal":
        value_decimal: Any = row.get("value_decimal")
        if value_decimal is None:
            return ""
        return _decimal_to_string(value_decimal)

    if value_type_name in {"bool", "boolean"}:
        value_bool: Any = row.get("value_bool")
        if value_bool is None:
            return ""
        return "True" if bool(value_bool) else "False"

    if value_type_name == "datetime":
        return _datetime_to_snapshot_string(row.get("value_datetime")) or ""

    # Fallback for text-like values.
    value_text: Any = row.get("value_text")
    return "" if value_text is None else str(value_text)


def _fetch_one_dict(sql: str, params: list[Any]) -> Optional[dict[str, Any]]:
    with connection.cursor() as cursor:
        cursor.execute(sql, params)
        row: Optional[tuple[Any, ...]] = cursor.fetchone()
        if row is None:
            return None

        description = cursor.description
        if description is None:
            raise RuntimeError("Query did not return column metadata.")

        column_names: list[str] = [column[0] for column in description]
        return dict(zip(column_names, row))


def _fetch_all_dicts(sql: str, params: list[Any]) -> list[dict[str, Any]]:
    with connection.cursor() as cursor:
        cursor.execute(sql, params)
        rows: list[tuple[Any, ...]] = cursor.fetchall()

        description = cursor.description
        if description is None:
            raise RuntimeError("Query did not return column metadata.")

        column_names: list[str] = [column[0] for column in description]

    return [dict(zip(column_names, row)) for row in rows]


def _datetime_to_snapshot_string(value: Any) -> Optional[str]:
    if value is None:
        return None

    if not isinstance(value, datetime):
        return str(value)

    converted_value: datetime = value
    if timezone.is_aware(converted_value):
        converted_value = converted_value.astimezone(datetime_timezone.utc).replace(
            tzinfo=None
        )

    return converted_value.replace(microsecond=0).isoformat()


def _decimal_to_string(value: Any) -> str:
    rendered: str
    if isinstance(value, Decimal):
        rendered = format(value, "f")
    else:
        rendered = str(value)

    if "." not in rendered:
        return rendered

    trimmed: str = rendered.rstrip("0")
    if trimmed.endswith("."):
        trimmed += "0"

    return trimmed


def _decimal_to_float(value: Any) -> float:
    if value is None:
        return 0.0

    if isinstance(value, Decimal):
        return float(value)

    return float(value)


def _optional_string(value: Any) -> Optional[str]:
    if value is None:
        return None

    rendered: str = str(value)
    return rendered if rendered != "" else None


def _coerce_float(value: Any) -> float:
    if value is None:
        return 0.0

    return float(value)


def _coerce_attributes(value: Any) -> dict[str, str]:
    if not isinstance(value, dict):
        return {}

    coerced: dict[str, str] = {}
    for key, item in value.items():
        coerced[str(key)] = "" if item is None else str(item)

    return coerced
