# Generated by Django 6.0.2 on 2026-03-17 15:30

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, db_column='bio', null=True)),
                ('avatar', models.ImageField(blank=True, db_column='avatar_url', default='', max_length=512, upload_to=core.storage.avatar_upload_to)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.RESTRICT, to='core.city')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': True,
                'indexes': [models.Index(fields=['city'], name='fk_user_profiles_city')],
            },
        ),
    ]
