# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, db_column='bio', null=True)),
                ('avatar_url', models.CharField(db_column='avatar_url', max_length=512)),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': False,
            },
        ),
    ]
