# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, db_column='details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('status_id', models.BigAutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='status_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'report_status',
                'managed': False,
            },
        ),
    ]
