# Generated by Django 6.0.2 on 2026-03-21 00:52

import common.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('messaging', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('status_id', common.fields.UnsignedBigAutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='status_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'report_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', common.fields.UnsignedBigAutoField(db_column='report_id', primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, db_column='details', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('action', models.ForeignKey(blank=True, db_column='action_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='moderation.moderationaction')),
                ('conversation', models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='messaging.conversation')),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='listings.listing')),
                ('reporter_user', models.ForeignKey(db_column='reporter_user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, to='reports.reportstatus')),
            ],
            options={
                'db_table': 'reports',
                'managed': True,
                'indexes': [models.Index(fields=['reporter_user'], name='ix_reports_reporter'), models.Index(fields=['conversation'], name='ix_reports_conversation'), models.Index(fields=['listing'], name='ix_reports_listing'), models.Index(fields=['action'], name='fk_reports_action'), models.Index(fields=['status'], name='fk_reports_status')],
            },
        ),
    ]
