# Generated by Django 6.0.2 on 2026-03-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reportstatus',
            options={'managed': True},
        ),
    ]
