# Generated by Django 6.0.2 on 2026-03-20 20:47

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=common.fields.UnsignedBigAutoField(db_column='report_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportstatus',
            name='status_id',
            field=common.fields.UnsignedBigAutoField(db_column='status_id', primary_key=True, serialize=False),
        ),
    ]
