# Generated by Django 6.0.2 on 2026-03-21 00:52

import common.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', common.fields.UnsignedBigAutoField(db_column='conversation_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('user_a', models.ForeignKey(db_column='user_a_id', on_delete=django.db.models.deletion.RESTRICT, related_name='conversations_as_user_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(db_column='user_b_id', on_delete=django.db.models.deletion.RESTRICT, related_name='conversations_as_user_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', common.fields.UnsignedBigAutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('message_text', models.TextField(db_column='message_text')),
                ('sent_at', models.DateTimeField(db_column='sent_at', default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation')),
                ('sender_user', models.ForeignKey(db_column='sender_user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_a'], name='ix_conversations_user_a'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_b'], name='ix_conversations_user_b'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_a', 'created_at'], name='idx_conv_user_a_created'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_b', 'created_at'], name='idx_conv_user_b_created'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='uq_conversations_pair'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='ix_messages_conversation_sent'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_user'], name='ix_messages_sender'),
        ),
    ]
