# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.BigAutoField(db_column='conversation_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('message_text', models.TextField(db_column='message_text')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='sent_at')),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
    ]
