# Generated by Django 6.0.2 on 2026-03-20 20:47

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=common.fields.UnsignedBigAutoField(db_column='conversation_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=common.fields.UnsignedBigAutoField(db_column='message_id', primary_key=True, serialize=False),
        ),
    ]
