# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('action_id', models.BigAutoField(db_column='action_id', primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'moderation_actions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModerationActionType',
            fields=[
                ('action_type_id', models.BigAutoField(db_column='action_type_id', primary_key=True, serialize=False)),
                ('action_type_name', models.CharField(db_column='action_type_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'moderation_action_type',
                'managed': False,
            },
        ),
    ]
