# Generated by Django 6.0.2 on 2026-03-17 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationActionType',
            fields=[
                ('action_type_id', models.BigAutoField(db_column='action_type_id', primary_key=True, serialize=False)),
                ('action_type_name', models.CharField(db_column='action_type_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'moderation_action_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('action_id', models.BigAutoField(db_column='action_id', primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(db_column='actor_user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='moderation_actions_as_actor', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='listings.listing')),
                ('target_user', models.ForeignKey(blank=True, db_column='target_user_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('action_type', models.ForeignKey(db_column='action_type_id', on_delete=django.db.models.deletion.RESTRICT, to='moderation.moderationactiontype')),
            ],
            options={
                'db_table': 'moderation_actions',
                'managed': True,
                'indexes': [models.Index(fields=['actor_user'], name='ix_mod_actions_actor'), models.Index(fields=['listing'], name='ix_mod_actions_listing'), models.Index(fields=['target_user'], name='ix_mod_actions_target_user'), models.Index(fields=['action_type'], name='fk_mod_actions_action_type')],
            },
        ),
    ]
