# Generated by Django 6.0.2 on 2026-03-20 20:47

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action_id',
            field=common.fields.UnsignedBigAutoField(db_column='action_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moderationactiontype',
            name='action_type_id',
            field=common.fields.UnsignedBigAutoField(db_column='action_type_id', primary_key=True, serialize=False),
        ),
    ]
