# Generated by Django 6.0.2 on 2026-03-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValueType',
            fields=[
                ('value_type_id', models.BigAutoField(db_column='value_type_id', primary_key=True, serialize=False)),
                ('value_type_name', models.CharField(db_column='value_type_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'attribute_value_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('condition_id', models.BigAutoField(db_column='condition_id', primary_key=True, serialize=False)),
                ('condition_name', models.CharField(db_column='condition_name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'item_conditions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('slug', models.CharField(db_column='slug', max_length=255, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, db_column='parent_category_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.category')),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.BigAutoField(db_column='attribute_id', primary_key=True, serialize=False)),
                ('attribute_key', models.CharField(db_column='attribute_key', max_length=100, unique=True)),
                ('value_type', models.ForeignKey(db_column='value_type_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.attributevaluetype')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='catalog.category')),
            ],
            options={
                'db_table': 'attributes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AllowedAttributeValue',
            fields=[
                ('allowed_value_id', models.BigAutoField(db_column='allowed_value_id', primary_key=True, serialize=False)),
                ('allowed_value_label', models.CharField(db_column='allowed_value_label', max_length=80)),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute')),
            ],
            options={
                'db_table': 'allowed_attribute_values',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('attribute', 'allowed_value_label'), name='uq_allowed_attribute_values_attribute_value_pair')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category'], name='ix_categories_parent'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['value_type'], name='fk_attributes_value_type'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['category'], name='fk_attributes_category'),
        ),
    ]
