# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAttributeValue',
            fields=[
                ('allowed_value_id', models.BigAutoField(db_column='allowed_value_id', primary_key=True, serialize=False)),
                ('allowed_value_label', models.CharField(db_column='allowed_value_label', max_length=80)),
            ],
            options={
                'db_table': 'allowed_attribute_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.BigAutoField(db_column='attribute_id', primary_key=True, serialize=False)),
                ('attribute_key', models.CharField(db_column='attribute_key', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValueType',
            fields=[
                ('value_type_id', models.BigAutoField(db_column='value_type_id', primary_key=True, serialize=False)),
                ('value_type_name', models.CharField(db_column='value_type_name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'attribute_value_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('slug', models.CharField(db_column='slug', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('condition_id', models.BigAutoField(db_column='condition_id', primary_key=True, serialize=False)),
                ('condition_name', models.CharField(db_column='condition_name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'item_conditions',
                'managed': False,
            },
        ),
    ]
