# Generated by Django 6.0.2 on 2026-03-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedattributevalue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='attributevaluetype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='itemcondition',
            options={'managed': True},
        ),
    ]
