# Generated by Django 6.0.2 on 2026-03-20 20:47

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedattributevalue',
            name='allowed_value_id',
            field=common.fields.UnsignedBigAutoField(db_column='allowed_value_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_id',
            field=common.fields.UnsignedBigAutoField(db_column='attribute_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attributevaluetype',
            name='value_type_id',
            field=common.fields.UnsignedBigAutoField(db_column='value_type_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=common.fields.UnsignedBigAutoField(db_column='category_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemcondition',
            name='condition_id',
            field=common.fields.UnsignedBigAutoField(db_column='condition_id', primary_key=True, serialize=False),
        ),
    ]
