# Generated by Django 6.0.2 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingMetadataSnapshot',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('compiled_json', models.JSONField(db_column='compiled_json')),
                ('compiled_at', models.DateTimeField(auto_now_add=True, db_column='compiled_at')),
            ],
            options={
                'db_table': 'listing_metadata_snapshots',
                'managed': False,
            },
        ),
    ]
