# Generated by Django 6.0.2 on 2026-03-21 00:52

import common.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingMetadataSnapshot',
            fields=[
                ('id', common.fields.UnsignedBigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('compiled_json', models.JSONField(db_column='compiled_json')),
                ('compiled_at', models.DateTimeField(db_column='compiled_at', default=django.utils.timezone.now)),
                ('listing', models.OneToOneField(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'db_table': 'listing_metadata_snapshots',
                'managed': True,
            },
        ),
    ]
